<?xml version="1.0" encoding="utf-8"?><Database Name="QLKS" Class="QLKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-P250IPBQ;Initial Catalog=QLKS;Persist Security Info=True;User ID=sa" SettingsObjectName="BLL.Properties.Settings" SettingsPropertyName="QLKS_MainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chitietsudungdv" Member="chitietsudungdvs">
    <Type Name="chitietsudungdv">
      <Column Name="id_datphong" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_dichvu" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngay_thue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tong_tien_dv" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="datphong_chitietsudungdv" Member="datphong" ThisKey="id_datphong" OtherKey="id_datphong" Type="datphong" IsForeignKey="true" />
      <Association Name="dichvu_chitietsudungdv" Member="dichvu" ThisKey="id_dichvu" OtherKey="id_dichvu" Type="dichvu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thietbi" Member="thietbis">
    <Type Name="thietbi">
      <Column Name="id_thietbi" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_thietbi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="thietbi_chitietsudungtb" Member="chitietsudungtbs" ThisKey="id_thietbi" OtherKey="id_thietbi" Type="chitietsudungtb" />
    </Type>
  </Table>
  <Table Name="dbo.chitietsudungtb" Member="chitietsudungtbs">
    <Type Name="chitietsudungtb">
      <Column Name="id_datphong" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_thietbi" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngay_thue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tong_tien_tb" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="thietbi_chitietsudungtb" Member="thietbi" ThisKey="id_thietbi" OtherKey="id_thietbi" Type="thietbi" IsForeignKey="true" />
      <Association Name="datphong_chitietsudungtb" Member="datphong" ThisKey="id_datphong" OtherKey="id_datphong" Type="datphong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.datphong" Member="datphongs">
    <Type Name="datphong">
      <Column Name="id_datphong" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_nhanvien" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="id_khachhang" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="id_phong" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="check_in" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="check_out" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dat_coc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tien_phong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phu_thu_checkin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="phu_thu_checkout" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tong_tien_dv" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tong_tien_tb" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tong_tien_hoa_don" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tong_tien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="so_nguoi_o" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="loai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Association Name="datphong_chitietsudungdv" Member="chitietsudungdvs" ThisKey="id_datphong" OtherKey="id_datphong" Type="chitietsudungdv" />
      <Association Name="datphong_chitietsudungtb" Member="chitietsudungtbs" ThisKey="id_datphong" OtherKey="id_datphong" Type="chitietsudungtb" />
      <Association Name="khachhang_datphong" Member="khachhang" ThisKey="id_khachhang" OtherKey="id_khachhang" Type="khachhang" IsForeignKey="true" />
      <Association Name="nhanvien_datphong" Member="nhanvien" ThisKey="id_nhanvien" OtherKey="id_nhanvien" Type="nhanvien" IsForeignKey="true" />
      <Association Name="phong_datphong" Member="phong" ThisKey="id_phong" OtherKey="id_phong" Type="phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.datphongonline" Member="datphongonlines">
    <Type Name="datphongonline">
      <Column Name="id_datphong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_phong" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="check_in" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="check_out" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tong_tien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="so_nguoi_o" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ten_khachhang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_sinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="cmnd" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="gioi_tinh" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="phong_datphongonline" Member="phong" ThisKey="id_phong" OtherKey="id_phong" Type="phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dichvu" Member="dichvus">
    <Type Name="dichvu">
      <Column Name="id_dichvu" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_dichvu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="dichvu_chitietsudungdv" Member="chitietsudungdvs" ThisKey="id_dichvu" OtherKey="id_dichvu" Type="chitietsudungdv" />
    </Type>
  </Table>
  <Table Name="dbo.imgphong" Member="imgphongs">
    <Type Name="imgphong">
      <Column Name="id_loaiphong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_hinh" Type="System.String" DbType="VarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="loaiphong_imgphong" Member="loaiphong" ThisKey="id_loaiphong" OtherKey="id_loaiphong" Type="loaiphong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khachhang" Member="khachhangs">
    <Type Name="khachhang">
      <Column Name="id_khachhang" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_khachhang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_sinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="cmnd" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="gioi_tinh" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="khachhang_datphong" Member="datphongs" ThisKey="id_khachhang" OtherKey="id_khachhang" Type="datphong" />
    </Type>
  </Table>
  <Table Name="dbo.khachsan" Member="khachsans">
    <Type Name="khachsan">
      <Column Name="id" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dia_chi" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.loaiphong" Member="loaiphongs">
    <Type Name="loaiphong">
      <Column Name="id_loaiphong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_loai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="so_luong_nguoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mota" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="loaiphong_imgphong" Member="imgphongs" ThisKey="id_loaiphong" OtherKey="id_loaiphong" Type="imgphong" />
      <Association Name="loaiphong_phong" Member="phongs" ThisKey="id_loaiphong" OtherKey="id_loaiphong" Type="phong" />
    </Type>
  </Table>
  <Table Name="dbo.nhanvien" Member="nhanviens">
    <Type Name="nhanvien">
      <Column Name="id_nhanvien" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_nhanvien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_sinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gioi_tinh" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="nhanvien_datphong" Member="datphongs" ThisKey="id_nhanvien" OtherKey="id_nhanvien" Type="datphong" />
      <Association Name="nhanvien_taikhoan" Member="taikhoans" ThisKey="id_nhanvien" OtherKey="id_nhanvien" Type="taikhoan" />
    </Type>
  </Table>
  <Table Name="dbo.phong" Member="phongs">
    <Type Name="phong">
      <Column Name="id_phong" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_loaiphong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_tang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="gia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="phong_datphong" Member="datphongs" ThisKey="id_phong" OtherKey="id_phong" Type="datphong" />
      <Association Name="phong_datphongonline" Member="datphongonlines" ThisKey="id_phong" OtherKey="id_phong" Type="datphongonline" />
      <Association Name="loaiphong_phong" Member="loaiphong" ThisKey="id_loaiphong" OtherKey="id_loaiphong" Type="loaiphong" IsForeignKey="true" />
      <Association Name="tang_phong" Member="tang" ThisKey="id_tang" OtherKey="id_tang" Type="tang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.taikhoan" Member="taikhoans">
    <Type Name="taikhoan">
      <Column Name="id_taikhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_nhanvien" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ten_dang_nhap" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="mat_khau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="hoat_dong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quyen" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="nhanvien_taikhoan" Member="nhanvien" ThisKey="id_nhanvien" OtherKey="id_nhanvien" Type="nhanvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tang" Member="tangs">
    <Type Name="tang">
      <Column Name="id_tang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_tang" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="tang_phong" Member="phongs" ThisKey="id_tang" OtherKey="id_tang" Type="phong" />
    </Type>
  </Table>
  <Table Name="dbo.view_datphong2" Member="view_datphong2s">
    <Type Name="view_datphong2">
      <Column Name="id_datphong" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="check_in" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="check_out" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="tong_thoi_gian" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ten_nhanvien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ten_khachhang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Capnhat_chi_tiet_su_dung_dv" Method="Capnhat_chi_tiet_su_dung_dv">
    <Parameter Name="iddatphong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="iddv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Xoa_chi_tiet_su_dung_tb" Method="Xoa_chi_tiet_su_dung_tb">
    <Parameter Name="iddatphong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="idtb" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Capnhat_chi_tiet_su_dung_tb" Method="Capnhat_chi_tiet_su_dung_tb">
    <Parameter Name="iddatphong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="idtb" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Dat_Phong" Method="Dat_Phong">
    <Parameter Name="id_nhanvien" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="id_khachhang" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="id_phong" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="check_in" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="check_out" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="so_nguoi_o" Type="System.Int32" DbType="Int" />
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="dat_coc" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_chi_tiet_su_dung_dv" Method="Them_chi_tiet_su_dung_dv">
    <Parameter Name="id_datphong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="id_dvu" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ngaythue" Type="System.DateTime" DbType="Date" />
    <Parameter Name="so_luong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_chi_tiet_su_dung_tb" Method="Them_chi_tiet_su_dung_tb">
    <Parameter Name="id_datphong" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="id_tbi" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ngaythue" Type="System.DateTime" DbType="Date" />
    <Parameter Name="so_luong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_Dich_Vu" Method="Them_Dich_Vu">
    <Parameter Name="ten_dichvu" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_Khach_Hang" Method="Them_Khach_Hang">
    <Parameter Name="ten_khachhang" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngay_sinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="dia_chi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="sdt" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="cmnd" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="gioi_tinh" Type="System.String" DbType="NVarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_Phong" Method="Them_Phong">
    <Parameter Name="id_loaiphong" Type="System.Int32" DbType="Int" />
    <Parameter Name="id_tang" Type="System.Int32" DbType="Int" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="trangthai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_Thiet_Bi" Method="Them_Thiet_Bi">
    <Parameter Name="ten_thietbi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Tinh_Tong_Tien_DichVu" Method="Tinh_Tong_Tien_DichVu">
    <Parameter Name="id_datphong" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="tong_tien_dv" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Tinh_Tong_Tien_Phuthu" Method="Tinh_Tong_Tien_Phuthu">
    <Parameter Name="mychoose" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="id_datphong" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="tong_tien" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="tien_phuthu" Type="System.Double" DbType="Float" Direction="InOut" />
    <Parameter Name="tien_phuthu1" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Tinh_Tong_Tien_ThietBi" Method="Tinh_Tong_Tien_ThietBi">
    <Parameter Name="id_datphong" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="tong_tien_tb" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Update_TrangThaiPhong_1" Method="Update_TrangThaiPhong_1">
    <Parameter Name="idphong" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Xoa_chi_tiet_su_dung_dv" Method="Xoa_chi_tiet_su_dung_dv">
    <Parameter Name="iddatphong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="iddv" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Them_Nhan_Vien" Method="Them_Nhan_Vien">
    <Parameter Name="ten_nhanvien" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngay_sinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="sdt" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="gioi_tinh" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>